name = "RationalVectorFitting"
uuid = "52b1e31a-230f-50d6-be04-0f5494ddfff6"
authors = ["Pedro H. N. Vieira <phnvieira@proton.me>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"
